In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/User/Documents/devanasokan_fyp/datasource/top-10k-spotify-songs-2025-07-detailed.csv")

In [9]:
print(df.info)

<bound method DataFrame.info of        rank                               track_name                track_id  \
0         1                         Die With A Smile  2plbrEY59IikOBgBGLjaoe
1         2                                     DtMF  3sK8wGT43QFpWrvNQsrQya
2         3                       BIRDS OF A FEATHER  6dOtVTDdiauQNBQEDOtlAB
3         4  Clean Baby Sleep White Noise (Loopable)  0zirWZTcXBBwGsevrsIpvT
4         5                        BAILE INoLVIDABLE  2lTm559tuIvatlT1u0JYG2
...     ...                                      ...                     ...
9995   9996                              Gamesofluck  0rdWkO7ncrh1lrJGDmLq9L
9996   9997                                    Casio  44ZKnfWEkp7wPs035j4Tua
9997   9998           FANTASTIC BABY - Japanese ver.  26JeAi8xsSvLRoNsl9B8Js
9998   9999                                Miniskirt  6Yj8kVuVR3UPxx9r5eFEoV
9999  10000                                Backslide  6fNaHkjAxP6rI2sZhT7QJn

                                           artist_names  \
0                                  Lady Gaga|Bruno Mars
1                                             Bad Bunny
2                                         Billie Eilish
3     Dream Supplier|Baby Sleeps|Background White Noise
4                                             Bad Bunny
...                                                 ...
9995                                            Parcels
9996                                             Jungle
9997                                            BIGBANG
9998                                                AOA
9999                                  Twenty One Pilots

                                             artist_ids  \
0         1HY2Jd0NmPuamShAr6KMms|0du5cEVh5yTK9QJze8zA0C
1                                4q3ewBCX7sLwd24euuV69X
2                                6qqNVTkY8uBg9cP3Jd7DAH
3     6Cqtx9fpxzggIMuKn0RGCp|48zEowASEXWsK6lgP1xotZ|...
4                                4q3ewBCX7sLwd24euuV69X
...                                                 ...
9995                             3oKRxpszQKUjjaHz388fVA
9996                             59oA5WbbQvomJz2BuRG071
9997                             4Kxlr1PRlDKEB0ekOCyHgX
9998                             54gWVQFHf8IIqbjxAoOarN
9999                             3YQKmKGau1PzlVlkL1iodx

                              album_name                album_id  popularity  \
0                       Die With A Smile  10FLjwfpbxLmW8c25Xyc2N         100
1                   DeBÍ TiRAR MáS FOToS  5K79FLRUCSysQnVESLcTdb          98
2                   HIT ME HARD AND SOFT  7aJuG4TFXa2hmE4z1yxc3n          98
3     Best White Noise For Sleeping Baby  0NGHR9zjS5eFFlqtClA9VV          97
4                   DeBÍ TiRAR MáS FOToS  5K79FLRUCSysQnVESLcTdb          96
...                                  ...                     ...         ...
9995                         Gamesofluck  0ugE0qpkFDNLYFmNiUOOKA          70
9996                            For Ever  5gYCZgmXzzWXxOCb9fMfBm          70
9997                               ALIVE  7p5rDiIXiv1IcEMThKwsaM          70
9998                           MINISKIRT  6esB2DBt46m38ZycDPsn8D          70
9999                              Clancy  1KFWgQTw3EMTQebaaepVBI          70

     duration  explicit  ... valence    tempo duration_ms  time_signature  \
0        4:11         0  ...   0.535  157.969    251668.0             3.0
1        3:57         1  ...   0.032  136.020    140296.0             4.0
2        3:30         0  ...   0.438  104.978    210373.0             4.0
3        2:22         0  ...     NaN      NaN         NaN             NaN
4        6:07         1  ...   0.219  119.387    132831.0             3.0
...       ...       ...  ...     ...      ...         ...             ...
9995     5:48         0  ...   0.553  104.997    348093.0             4.0
9996     3:54         0  ...   0.765  115.989    234370.0             4.0
9997     3:51         0  ...   0.433  130.010    231627.0             4.0
9998     2:59         0  ...   0.963  119.992    179808.0             4.0
9999     3:00         0  ...   0.541   85.104    180000.0             4.0

      total_artist_followers  avg_artist_popularity  \
0                  121068459              91.000000
1                  105635803              99.000000
2                  121278701              93.000000
3                      25098              51.333333
4                  105635803              99.000000
...                      ...                    ...
9995                 1119687              72.000000
9996                 1768384              71.000000
9997                 6263195              71.000000
9998                  911391              62.000000
9999                25963932              85.000000

                                          artist_genres  \
0                                    ["art pop", "pop"]
1     ["latin", "reggaeton", "trap latino", "urbano ...
2                                    ['pop', 'art pop']
3                             ["native american music"]
4     ["latin", "reggaeton", "trap latino", "urbano ...
...                                                 ...
9995                                     ["indie soul"]
9996              ['indie soul', 'uk contemporary r&b']
9997                                          ["k-pop"]
9998                                          ["k-pop"]
9999       ['rock', 'modern rock', 'pop', 'pov: indie']

                                    main_genres  \
0                                           Pop
1                                         Latin
2                                           Pop
3     Easy Listening, Electronic, New Age, Rock
4                                         Latin
...                                         ...
9995                                        R&B
9996                                        R&B
9997                                        Pop
9998                                        Pop
9999                                  Pop, Rock

                                                 lyrics  metadata_overlap
0     Ooh, ooh\n\nI, I just woke up from a dream\nBu...             False
1     Eh-eh, he-eh, eh-eh, eh-eh\nOtro sunset bonito...             False
2     I want you to stay\n'Til I'm in the grave\n'Ti...             False
3                                                   NaN             False
4     Pensaba que contigo iba a envejecer\nEn otra v...             False
...                                                 ...               ...
9995  You sowed it slower to find your man\nBut fold...             False
9996  Casio, playing on my heart just like a Casio\n...              True
9997  夜が来た 目覚ましな\nWe gon' party like\nLi li li la la...             False
9998  Hey Hey Hey AOA\nHey Hey Hey\nBrave Sound (Dro...             False
9999  (I don't wanna)\n\nRat race, place to place, a...             False

[10000 rows x 33 columns]>

In [10]:
# Summary statistics (numerical)
df.describe()

,rank,popularity,explicit,copies,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,total_artist_followers,avg_artist_popularity
count,10000.00000,10000.000000,10000.000000,10000.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,9969.000000,1.000000e+04,10000.000000
mean,5000.50000,75.065700,0.263800,70.089300,0.633544,0.639333,5.313171,-7.073844,0.598756,0.088646,0.275565,0.044603,0.181010,0.511469,121.637453,213583.501856,3.915939,2.222812e+07,76.446787
std,2886.89568,4.348388,0.440714,169.137545,0.157657,0.194479,3.575884,4.107705,0.490175,0.091559,0.271579,0.166730,0.147435,0.242410,28.351274,60041.026498,0.367680,3.564868e+07,10.307408
min,1.00000,70.000000,0.000000,1.000000,0.000000,0.000190,0.000000,-54.341000,0.000000,0.000000,0.000004,0.000000,0.019000,0.000000,0.000000,37929.000000,0.000000,1.790000e+02,19.000000
25%,2500.75000,72.000000,0.000000,2.000000,0.534000,0.518000,2.000000,-8.298000,0.000000,0.035400,0.042200,0.000000,0.095200,0.320000,99.824000,175427.000000,4.000000,2.117612e+06,69.000000
50%,5000.50000,74.000000,0.000000,6.000000,0.650000,0.662000,5.000000,-6.264000,1.000000,0.050100,0.181000,0.000003,0.123000,0.509000,120.098000,208267.000000,4.000000,7.977994e+06,77.000000
75%,7500.25000,77.000000,1.000000,47.000000,0.749000,0.786000,8.000000,-4.819000,1.000000,0.097400,0.452000,0.000410,0.215000,0.706000,139.765000,241688.000000,4.000000,2.439491e+07,84.000000
max,10000.00000,100.000000,1.000000,2655.000000,0.984000,1.000000,11.000000,2.605000,1.000000,0.918000,0.996000,1.000000,0.989000,0.991000,220.099000,811077.000000,5.000000,2.960635e+08,100.000000

In [11]:
# Summary including categorical
df.describe(include='all')

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,...,valence,tempo,duration_ms,time_signature,total_artist_followers,avg_artist_popularity,artist_genres,main_genres,lyrics,metadata_overlap
count,10000.00000,10000,10000,10000,10000,9999,10000,10000.000000,10000,10000.000000,...,9969.000000,9969.000000,9969.000000,9969.000000,1.000000e+04,10000.000000,10000,9975,9583,10000
unique,NaN,9613,10000,5386,5388,6925,7104,NaN,417,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2625,272,9525,2
top,NaN,Stay,2plbrEY59IikOBgBGLjaoe,Taylor Swift,06HL4z0CvFAxyc27GXpf02,MUSIC,0fSfkmx0tdPqFYkJuNX74a,NaN,3:08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[""k-pop""]",Pop,I walk a lonely road\nThe only one that I have...,False
freq,NaN,6,1,108,108,30,30,NaN,95,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,221,1938,3,9566
mean,5000.50000,NaN,NaN,NaN,NaN,NaN,NaN,75.065700,NaN,0.263800,...,0.511469,121.637453,213583.501856,3.915939,2.222812e+07,76.446787,NaN,NaN,NaN,NaN
std,2886.89568,NaN,NaN,NaN,NaN,NaN,NaN,4.348388,NaN,0.440714,...,0.242410,28.351274,60041.026498,0.367680,3.564868e+07,10.307408,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,70.000000,NaN,0.000000,...,0.000000,0.000000,37929.000000,0.000000,1.790000e+02,19.000000,NaN,NaN,NaN,NaN
25%,2500.75000,NaN,NaN,NaN,NaN,NaN,NaN,72.000000,NaN,0.000000,...,0.320000,99.824000,175427.000000,4.000000,2.117612e+06,69.000000,NaN,NaN,NaN,NaN
50%,5000.50000,NaN,NaN,NaN,NaN,NaN,NaN,74.000000,NaN,0.000000,...,0.509000,120.098000,208267.000000,4.000000,7.977994e+06,77.000000,NaN,NaN,NaN,NaN
75%,7500.25000,NaN,NaN,NaN,NaN,NaN,NaN,77.000000,NaN,1.000000,...,0.706000,139.765000,241688.000000,4.000000,2.439491e+07,84.000000,NaN,NaN,NaN,NaN
max,10000.00000,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,1.000000,...,0.991000,220.099000,811077.000000,5.000000,2.960635e+08,100.000000,NaN,NaN,NaN,NaN

In [12]:
missing_summary = df.isnull().sum().to_frame(name='Missing Count')
missing_summary['Percentage (%)'] = (missing_summary['Missing Count'] / len(df)) * 100
missing_summary.sort_values(by='Missing Count', ascending=False)

                        Missing Count  Percentage (%)
lyrics                            417            4.17
acousticness                       31            0.31
key                                31            0.31
energy                             31            0.31
danceability                       31            0.31
mode                               31            0.31
time_signature                     31            0.31
duration_ms                        31            0.31
instrumentalness                   31            0.31
loudness                           31            0.31
valence                            31            0.31
liveness                           31            0.31
tempo                              31            0.31
speechiness                        31            0.31
main_genres                        25            0.25
album_name                          1            0.01
rank                                0            0.00
copies                              0            0.00
release_date                        0            0.00
album_type                          0            0.00
isrc                                0            0.00
explicit                            0            0.00
album_id                            0            0.00
popularity                          0            0.00
duration                            0            0.00
track_id                            0            0.00
artist_names                        0            0.00
track_name                          0            0.00
artist_ids                          0            0.00
avg_artist_popularity               0            0.00
total_artist_followers              0            0.00
artist_genres                       0            0.00
metadata_overlap                    0            0.00

In [ ]:
# Check for duplicates
print(df.duplicated().sum())

0

In [3]:
# 1. Check if lyrics start with Track Name or Artist Name
def check_metadata_overlap(row):
    lyrics = str(row['lyrics']).lower()
    track = str(row['track_name']).lower()
    artist = str(row['artist_names']).lower().split('|')[0] # check first artist
    
    starts_with_track = lyrics.startswith(track)
    starts_with_artist = lyrics.startswith(artist)
    
    return starts_with_track or starts_with_artist

In [4]:
df['metadata_overlap'] = df.apply(check_metadata_overlap, axis=1)
print(f"Number of songs starting with metadata: {df['metadata_overlap'].sum()}")
print(df[df['metadata_overlap']][['track_name', 'lyrics']].head())

Number of songs starting with metadata: 434
               track_name                                             lyrics
16            Abracadabra  Abracadabra, abracadabra\nAbracadabra, abracad...
23          Te Quería Ver  Te quería ver\nSolo un ratito, volverte a tene...
28                Anxiety  Anxiety\nKeep on trying me\nI feel it quietly\...
30                ME JALO  Fuerza Regida\n\nChula, qué bellos ojos\nVen, ...
50  Every Breath You Take  Every breath you take\nAnd every move you make...

In [5]:
short_lyrics = df[df['lyrics'].str.len() < 50]
print(f"Number of very short lyrics: {len(short_lyrics)}")
print(short_lyrics[['track_name', 'lyrics']])

Number of very short lyrics: 4
                   track_name                   lyrics
1537  Never Gonna Give You Up            *Rickrolling*
2266                  (dream)           (Instrumental)
8464  Mia & Sebastian’s Theme  Mia & Sebastian’s Theme
9462         Death Is No More             Blessed Mane

In [6]:
# Check for leftovers of timestamps/brackets
leftovers = df['lyrics'].str.contains(r'\[|\]|\{|\}', na=False).sum()
print(f"Number of songs with remaining brackets: {leftovers}")

Number of songs with remaining brackets: 31

In [7]:
# Check for instrumentals
instrumentals = df['lyrics'].str.contains(r'instrumental', case=False, na=False).sum()
print(f"Number of instrumental tags: {instrumentals}")

Number of instrumental tags: 10

In [8]:
# Check for "Lyrics by", "Produced by" etc again but as phrases
credits_count = df['lyrics'].str.contains(r'lyrics by|produced by|written by|writer\(s\)', case=False, na=False).sum()
print(f"Number of songs with credits: {credits_count}")

Number of songs with credits: 3